### ISSUE TITLE
unsupported tag format

### ISSUE THREAD

**Issue by ldez** [jingyugao/rowserrcheck#22]
Hello,

the current tags (`0.1`, `1.1.0`) don't work with the go modules system.

could you add tags `v1.1.0` and `v0.1`?

Thank you.

**Comment by ldez** [comment]
friendly ping @jingyugao

**Comment by jingyugao** [comment]
updated

**Comment by ldez** [comment]
You have missed `1.1.0`

https://github.com/jingyugao/rowserrcheck/tags

**Comment by jingyugao** [comment]
> In fact, you have
> 
> * 1.1.0 on [d907ca7](https://github.com/jingyugao/rowserrcheck/commit/d907ca737bb10a42b7e263244d25f950bb8f1427)
> * v0.1 on [d907ca7](https://github.com/jingyugao/rowserrcheck/commit/d907ca737bb10a42b7e263244d25f950bb8f1427)
> * 0.1 on [8071922](https://github.com/jingyugao/rowserrcheck/commit/80719221d9bae23efd8914811e4a7cc75c7c2bec)
> 
> but `v0.1` must be on [8071922](https://github.com/jingyugao/rowserrcheck/commit/80719221d9bae23efd8914811e4a7cc75c7c2bec)
> 
> and `v1.1.0` must be on [d907ca7](https://github.com/jingyugao/rowserrcheck/commit/d907ca737bb10a42b7e263244d25f950bb8f1427)
I just add new tag v1.1.0 on d907ca7.PTAL

**Comment by ldez** [comment]
v0.1 is still on the wrong commit, but now it's too late to fix that.

Thank you anyway for the tag `v1.1.0`
