### ISSUE TITLE
SSA and generics (go1.18)

### ISSUE THREAD

**Issue by ldez** [jingyugao/rowserrcheck#24]
Currently, SSA is not working with generics.

So your linter produces a panic when it is used with generics.

There is an issue open about that in the Go repository: https://github.com/golang/go/issues/48525

Inside golangci-lint, we have disabled your linters: https://github.com/golangci/golangci-lint/issues/2649

You have 2 solutions:
- waiting for a version of SSA that will support generics
- dropping the SSA analyzers and using something else to analyze the code.

Related to https://github.com/golang/go/issues/50558

**Comment by ldez** [comment]
Updating Update golang.org/x/tools to the newest version is not enough.
Have you tried to test your linter with generics?

**Comment by fho** [comment]
@ldez I did.
When running it on code containing generics, the execution now succeeds and it also still finds issues, if rows are not closed.

**Comment by ldez** [comment]
what I can say: in golangci-lint, this update is not enough to fix the problem of this linter.

There are several syntaxes to validate for the support of generics.

**Comment by fho** [comment]
@ldez could you provide a codesnippet for that rowserrcheck fails?

**Comment by ldez** [comment]
SSA has been updated and it seems to work inside golangci-lint.

**Comment by ldez** [comment]
in fact, the problem is still here

**Comment by fho** [comment]
@ldez what is the problem? How can I reproduce the problem only with rowserrcheck?

**Comment by ldez** [comment]
```go

import (
	"database/sql"
)

func RowsErrNotChecked(db *sql.DB, a int) {
	rows, _ := db.Query("select id from tb")
	for rows.Next() {

	}
}

func RowsErrNotCheckedG[T ~int64](db *sql.DB, a T) {
	rows, _ := db.Query("select id from tb")
	for rows.Next() {

	}
}
```

**Comment by fho** [comment]
@ldez I can't reproduce an issue with that snippet.
rowserrcheck does not panic and it complains about a missing `rows.Err` check. It works as expected.

```sh
[fho@ltop rowserrcheck]$ git rev-parse HEAD
fa9179529ab817c3359a4f5beeec91546f71d602
[fho@ltop rowserrcheck]$ cat /tmp/main.go
package main

import (
	"database/sql"
)

func RowsErrNotChecked(db *sql.DB, a int) {
	rows, _ := db.Query("select id from tb")
	for rows.Next() {

	}
}

func RowsErrNotCheckedG[T ~int64](db *sql.DB, a T) {
	rows, _ := db.Query("select id from tb")
	for rows.Next() {

	}
}
[fho@ltop rowserrcheck]$ go run main.go -- /tmp/main.go
/tmp/main.go:8:21: rows.Err must be checked
exit status 3
```

**Comment by ldez** [comment]
With the sample, you must have 2 reports, currently, you only have one.
The problem is not a panic.

**Comment by fho** [comment]
@ldez right, but this is not blocking to enable rowserrcheck in golangci-lint again, is it?
The linter does not panic anymore when it encounters generics.

**Comment by ldez** [comment]
It is blocking.
The linter doesn't work as expected with generics, so we will not enable this linter like the others with the same problem.

False negatives are worse than false positives.
